/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

/**
 * @fileoverview 全局组件类型声明文件
 * @description 
 * 本文件由 vite-plugin-uni-components 插件自动生成，用于提供 Vue 3 全局组件的 TypeScript 类型支持
 * 
 * 生成信息：
 * - 生成工具：vite-plugin-uni-components
 * - 生成时间：构建时自动生成
 * - 更新策略：每次构建时重新生成，请勿手动修改
 * 
 * 功能说明：
 * 1. 为全局注册的组件提供类型声明
 * 2. 支持 TypeScript 智能提示和类型检查
 * 3. 确保组件在模板中的正确使用
 * 4. 提升开发体验和代码质量
 * 
 * 使用方式：
 * - 在 Vue 组件中直接使用声明的组件，无需手动导入
 * - TypeScript 会自动提供类型提示和检查
 * - 支持在模板和脚本中使用
 * 
 * 注意事项：
 * - 此文件为自动生成，手动修改会被覆盖
 * - 新增全局组件后需要重新构建生成类型声明
 * - 确保组件路径正确，避免类型错误
 * 
 * @see https://github.com/vuejs/core/pull/3399 Vue 3 全局组件类型支持
 * @see https://github.com/uni-helper/vite-plugin-uni-components 插件文档
 */
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399

/**
 * 空导出声明
 * 用于确保此文件作为模块文件处理，避免 TypeScript 编译错误
 */
export {}

/**
 * Vue 3 模块声明扩展
 * 通过模块扩展方式为 Vue 添加全局组件类型定义
 * 
 * 模块说明：
 * - 扩展 'vue' 模块的 GlobalComponents 接口
 * - 提供全局组件的完整类型信息
 * - 支持组件属性、事件、插槽的类型推断
 */
declare module 'vue' {
  /**
   * 全局组件接口定义
   * 包含所有在项目中全局注册的组件类型声明
   * 
   * 接口特性：
   * - 自动类型推断：基于组件实际定义生成类型
   * - 智能提示：IDE 中提供完整的组件属性提示
   * - 类型安全：编译时检查组件使用的正确性
   * - 热重载支持：组件变更时类型自动更新
   */
  export interface GlobalComponents {
    /**
     * DemoBlock 组件类型声明
     * 
     * 组件说明：
     * - 用途：用于演示代码块的包装组件
     * - 位置：./src/components/demo-block/demo-block.vue
     * - 功能：提供代码示例的展示容器，支持代码高亮和复制功能
     * 
     * 使用示例：
     * ```vue
     * <template>
     *   <DemoBlock title="按钮示例">
     *     <wd-button type="primary">主要按钮</wd-button>
     *   </DemoBlock>
     * </template>
     * ```
     * 
     * 主要特性：
     * - 支持自定义标题和描述
     * - 提供代码示例的展示区域
     * - 集成代码高亮和复制功能
     * - 响应式布局适配
     */
    DemoBlock: typeof import('./src/components/demo-block/demo-block.vue')['default']

    /**
     * PageWraper 组件类型声明
     * 
     * 组件说明：
     * - 用途：页面包装器组件，提供统一的页面布局结构
     * - 位置：./src/components/page-wraper/page-wraper.vue
     * - 功能：为页面提供标准的布局容器，包含头部、内容区域等
     * 
     * 使用示例：
     * ```vue
     * <template>
     *   <PageWraper title="组件列表" show-back>
     *     <div>页面内容</div>
     *   </PageWraper>
     * </template>
     * ```
     * 
     * 主要特性：
     * - 统一的页面布局结构
     * - 支持自定义页面标题
     * - 可选的返回按钮功能
     * - 响应式设计和移动端适配
     * - 集成页面导航和面包屑功能
     */
    PageWraper: typeof import('./src/components/page-wraper/page-wraper.vue')['default']

    /**
     * WdPrivacyPopup 组件类型声明
     * 
     * 组件说明：
     * - 用途：隐私政策弹窗组件，用于用户隐私授权
     * - 位置：./src/components/wd-privacy-popup/wd-privacy-popup.vue
     * - 功能：显示隐私政策内容，获取用户同意授权
     * 
     * 使用示例：
     * ```vue
     * <template>
     *   <WdPrivacyPopup 
     *     :visible="showPrivacy" 
     *     @confirm="handlePrivacyConfirm"
     *     @cancel="handlePrivacyCancel"
     *   />
     * </template>
     * ```
     * 
     * 主要特性：
     * - 符合隐私法规要求的弹窗设计
     * - 支持自定义隐私政策内容
     * - 提供同意和拒绝的用户交互
     * - 记录用户隐私选择状态
     * - 支持多语言国际化
     * - 移动端友好的弹窗样式
     * 
     * 法律合规：
     * - 符合 GDPR、CCPA 等隐私法规要求
     * - 支持用户隐私权利管理
     * - 提供透明的数据处理说明
     */
    WdPrivacyPopup: typeof import('./src/components/wd-privacy-popup/wd-privacy-popup.vue')['default']
  }
}
