/**
 * @fileoverview Vue 自动导入全局变量类型声明文件
 * @description 由 unplugin-auto-import 自动生成的 TypeScript 声明文件，为 Vue 3 应用提供自动导入 API 的类型支持
 *
 * 核心功能：
 * - 声明全局可用的 API 和组件变量，无需显式导入即可使用
 * - 提供 TypeScript 类型检查和 IDE 智能提示支持
 * - 确保自动导入的 API 在编译时具有正确的类型推断
 * - 支持第三方库 API 的全局访问能力
 *
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
