/**
 * @fileoverview Vue 全局组件类型声明文件
 * @description 由 unplugin-vue-components 自动生成的 TypeScript 声明文件，为 Vue 3 应用提供全局组件的类型支持
 *
 * 核心功能：
 * - 扩展 Vue 模块的 GlobalComponents 接口，提供全局组件的 TypeScript 类型声明
 * - 支持组件自动导入功能的类型检查和 IDE 智能提示
 * - 确保在模板中使用的全局组件具有正确的类型推断
 *
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
